<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>Fargowiltas</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Content\Buffs\CoolCrabBuff.png" />
    <None Remove="Content\Items\Vanity\CrabSizedGlasses.png" />
    <None Remove="Content\Projectiles\CoolCrab.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Localization\pt-BR\" />
    <Folder Include="Localization\zh-Hans\" />
    <Folder Include="Localization\ru-RU\" />
  </ItemGroup>
</Project>